[new]
title = "GeekNews ─ 최신글"
url = "https://news.hada.io/new"
entrySelector = "table tbody tr.topic"
titleSelector = "td.topictitle a h1"
linkSelector = "td.topictitle a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "td.topictitle"
titleSelector = "h1"
linkSelector = "a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[ask]
title = "GeekNews Ask"
url = "https://news.hada.io/ask"
entrySelector = "table tbody tr.topic"
titleSelector = "td.topictitle a h1"
linkSelector = "td.topictitle a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[weekly]
title = "GeekNews Weekly"
url = "https://news.hada.io/weekly"
entrySelector = "table tbody tr.title"
titleSelector = "a.u.keepall"
linkSelector = "td a.u.keepall"
contentSelector = "tr.title"
waitUntil = "networkidle"
